on:
  push
#    branches:
#- master
jobs:
  test-build:
    uses: ./.github/workflows/maven.yml
    secrets:
      ASSIST_EMAIL: ${{secrets.ASSIST_EMAIL}}
      ASSIST_GENERATOR: ${{secrets.ASSIST_GENERATOR}}
      ASSIST_PASSWORD: ${{secrets.ASSIST_PASSWORD}}
      ASSIST_VALIDATION: ${{secrets.ASSIST_VALIDATION}}
      ASSIST_VIEWSTATE: ${{secrets.ASSIST_VIEWSTATE}}
      DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
  deploy:
    if: github.branch == 'master'
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true -f pom.xml
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./target/SockApplication*.jar"
          target: /home/daan/DiscordBots/SockBot
          overwrite: true
          strip_components: 1
      - name: Rename and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/daan/DiscordBots/SockBot
            mv SockApplication.jar SockApplication.jar.original
            mv SockApplication*.jar SockApplication.jar
            systemctl restart sockbot.service